### ISSUE TITLE
Better Playlist functionality and file management

### ISSUE THREAD

**Issue by parulina** [BardMusicPlayer/BardMusicPlayer#3]
At the moment, the playlist functionality is rudimentary compared to existing media applications with playlists. No drag and drop (not a good one at least), finnicky with saving and loading, cannot export/import and cannot change the entered data. While the way the data is stored is fine (file path and track number) and should not be changed, the way the data is shown and manipulated could be improved by a lot. So, here is a proposition to improve the functionality of the Playlist.
- [ ] Drag and drop support, including drop marker and external midi files support. You should be able to add the loaded midi file in to the playlist and reorder it with other entries. You should also be able to drag a midi file (from windows explorer) in to the list and add it.
- [ ] Able to change track number, preferably by using NumericUpDown control.
- [ ] Able to easily back up and restore the playlist. Perhaps by writing the playlist to a file next to the executable? Figure this out.
- [x] Able to specify a pause in-between playlist entries.

Other ideas welcome. If you would like to work on this, feel free to ask for advice of the code base.

**Comment by amzrigh** [comment]
I have a suggestion for file management! As it stands, it's kinda difficult to distinguish various file traits (# of players, intended instruments by track, etc) when the only way to make note of that is in the file name.

Since I'm pretty sure the MIDI standard doesn't have built-in metadata (if I'm mistaken, that's some work saved!), the best solution that occurs to me is to create and use a wrapper file containing the MIDI and a metadata file. The metadata file would just be something easily-parsable, containing information like song title, composer, arranger, track descriptions, publish date/revision number, notes from the arranger, and whatever else. Then BMP could read that data, present it, and sort/filter by it.

I know there are lots of potential solutions here; if you've got a better idea, then awesome! That's why I led with the problem. I don't have the coding skill to implement it myself, but I do have project management experience, so I could help by writing up more detailed specifications.

**Comment by GiR-Zippo** [comment]
@parulina 
Wrote a small playlist load and save function for the BMP 1.4 branch at https://github.com/BardMusicPlayer/BardMusicPlayer/commit/d281afdaf78070413fa95b27200ec9670e36a9cc
[PlaylistLoadSave.txt](https://github.com/BardMusicPlayer/BardMusicPlayer/files/6505028/PlaylistLoadSave.txt)
It will give you two additional buttons on top of the playlist to load and save your playlist. The playlist is a simple text file with song and track in it.

**Comment by trotlinebeercan** [comment]
This ticket is pretty outdated. Meant for 1.x, as we move into 2.x, a new playlist system will be developed. Closing.
